"""add cartype

Revision ID: 5946c8f43a03
Revises: 
Create Date: 2024-05-28 13:52:29.003467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5946c8f43a03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('car_type', sa.Enum('MECHANIC', 'AUTO', name='cartype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('telegram', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_from', sa.String(), nullable=False),
    sa.Column('address_to', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CANCEL', name='status'), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_user', sa.BigInteger(), nullable=False),
    sa.Column('id_order_message', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('driver')
    op.drop_table('client')
    # ### end Alembic commands ###
