"""update cartype

Revision ID: 8229b26f8703
Revises: 5946c8f43a03
Create Date: 2024-05-28 14:31:02.083467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8229b26f8703'
down_revision: Union[str, None] = '5946c8f43a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_auto', sa.Boolean(), nullable=False))
    op.drop_column('client', 'car_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('car_type', postgresql.ENUM('MECHANIC', 'AUTO', name='cartype'), autoincrement=False, nullable=False))
    op.drop_column('client', 'is_auto')
    # ### end Alembic commands ###
